import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
const storageClient =  new Web3Storage({ token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDNjZTMwOTE5YTY5NGM1OWFlNmZCOTQzNmJlOWJDNTk4MDVEMTQ5NEYiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NDk1ODUwMjUzNTcsIm5hbWUiOiJMaWNlbnRhIn0.rHktpIH9NXQfFzFChE4l9KBCRbSpCGgRZggr99B9qIQ' })

export default storageClient;